### ISSUE TITLE
Add semver tags

### ISSUE THREAD

**Issue by nestorsokil** [rwynn/gtm#19]
Hey, do you mind adding some version tags to allow explicit vgo dependency declaration on your repo? Like, say, a `v1.0.0` for current `master`? Thanks.

**Comment by rwynn** [comment]
Hi, I will look into it.  Currently, it's a bit confusing since the `leafny` branch (based on the MongoDB go driver) is actually newer code than `master` (based on longstanding community mgo driver).  

Going forward I think the MongoDB driver will have more support.  So, I think I might move the current master in a branch and tag that `1.0.0` for those using it.  Then merge `leafny` into master and tag that `2.0.0`.    

Do you see any problems with that approach?  Besides potentially breaking those who might be building from master currently?

**Comment by rwynn** [comment]
Just for your reference (you may already know this), I currently link this project into a consumer using `go get` with a branch reference to pin the latest commit from that branch in the consuming project.  

In root of consuming project...
```
go get github.com/rwynn/gtm@leafny
```

updates my go.mod to...

https://github.com/rwynn/monstache/blob/rel6/go.mod

```
github.com/rwynn/gtm v0.0.0-20190808013136-41d259549857
```

**Comment by nestorsokil** [comment]
> Do you see any problems with that approach? Besides potentially breaking those who might be building from master currently?

Nope, just maybe while the `leafny` stuff is in development don't tag it `2.0.0` but maybe smth like `2.0.0-alpha1`. Other than that, up to you, thanks. :)

**Comment by rwynn** [comment]
@nestorsokil actually gtm integration with the new MongoDB driver stuff is no longer in development.  I am using it with the `rwynn/monstache` project and it has the same features plus more support for newer MongoDB versions.  I recommend using it over the community `mgo` driver now that the MongoDB driver has reached `v1.1.0`.  

I created 2 tagged releases - one for each flavor.   Please let me know if this works for you.

**Comment by nestorsokil** [comment]
@rwynn that's great, thanks!
